### ISSUE TITLE
Switch to icon fonts

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina-ui#82]
* Replace all svg images with icon font references
* Generate icon fonts from svg using something like https://github.com/tancredi/fantasticon

**Comment by philipstaffordwood** [comment]
progress: so far so good,

I'm going to suggest we keep the SVG images for some the left hand menu items product logos.

**Is this OK?**

LHS is original, RHS is refactored:

![image](https://user-images.githubusercontent.com/11496482/104644221-26cdf300-56b6-11eb-897a-bda505c624e2.png)

Normal webfonts are one color per glyph (1) and some of these icons don't work well in one-color.
There are some tricks possible to overlay two or three glyphs with multiple colors, but not sure if that's worth the trouble.

The two icons missing in the screenshot have conversion issues with https://github.com/tancredi/fantasticon (a few of the icons do - I'll look for fixes for the individual glyphs when most of the work is done).

So far the infographic icons seem well suited to using webfonts: in the screenshot the cargo-ship-50 icon suffers a bit of degradation from being one color, but it seems acceptable (in this case we could tweak the source SVG outline a bit to work better).

(1) Multi-color fonts are possible, but from a quick look [it looks](https://www.colorfonts.wtf/#section4) like Chrome support might be an issue. Happy to dig further, but not sure if this will be good bang-for-buck as we'd still need to look at the tooling for font-creation.

**Comment by moshloop** [comment]
single color fonts are 100%, and we should probably standardize on black, and then change the color using CSS when required
